test delete deploy

diff --git a/.github/workflows/delete-preview-deployment.yml b/.github/workflows/delete-preview-deployment.yml
--- a/.github/workflows/delete-preview-deployment.yml
+++ b/.github/workflows/delete-preview-deployment.yml
@@ -18,7 +18,7 @@ jobs:
           echo "APPLICATION_ID=$APPLICATION_ID" >> $GITHUB_ENV
       - name: Call API to delete PR data
         run: |
-          curl -X POST "http://your-dokploy-instance.com/api/application.delete" \
+          curl -X POST "https://dokploy.svuit.org/api/application.delete" \
             -H "Authorization: Bearer ${{secrets.TOKEN}}" \
             -H "Content-Type: application/json" \
             -d '{
@@ -28,10 +28,13 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - name: Delete GitHub Package
-        uses: paulushcgcj/delete-github-package@v1.0.0
-        with:
-          token: ${{ secrets.TOKEN }}
-          type: container
-          name: ${{github.repository.name}}%2F${{github.event.pull_request.number}}
-          version: 1.3.5-RC1
-          user: ${{ github.repository_owner }}
+        run: |
+          RESPONSE=$(curl -X DELETE \
+          -H "Authorization: Bearer ${{secrets.TOKEN}}" \
+          -H "Accept: application/vnd.github.v3+json" \
+          "https://api.github.com/users/Thanh8804/packages/container/img2md%2F${{ github.event.pull_request.number }}")
+          echo "API Response: $RESPONSE"
+          if echo "$RESPONSE" | jq -e .message >/dev/null 2>&1; then
+            echo "Error: $(echo "$RESPONSE" | jq -r '.message')"
+            exit 1
+          fi
